version: '3.8'

services:
  bmi_calculator:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile
    ports:
      - "4040:4040"  # Map port 4040 on the host to port 4040 in the container
    environment:
      - FLASK_ENV=development  # Enables Flask development mode

